name: List Plugins
on:
  workflow_call:
    outputs:
      plugin_list:
        description: "JSON array of plugin names"
        value: ${{ jobs.list.outputs.plugins }}

jobs:
  list:
    runs-on: ubuntu-latest
    outputs:
      plugins: ${{ steps.set-plugins.outputs.list }}
    steps:
      - uses: actions/checkout@v4
      - id: set-plugins
        run: |
          PLUGINS=$(ls -d mod/*/ | cut -d/ -f2 | jq -R -s -c 'split("\n")[:-1]')
          echo "list=$PLUGINS" >> $GITHUB_OUTPUT